import os
import sqlite3
import hashlib

# Secure password hashing fallback if bcrypt is not available
try:
    import bcrypt
    HAS_BCRYPT = True
except ImportError:
    HAS_BCRYPT = False

DB_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "database"))
DB_PATH = os.path.join(DB_DIR, "smart_vms.db")

def hash_password(password):
    """Hash a password using bcrypt if available, otherwise SHA-256."""
    if HAS_BCRYPT:
        salt = bcrypt.gensalt()
        return bcrypt.hashpw(password.encode('utf-8'), salt).decode('utf-8')
    else:
        # Fallback SHA-256 with simple salt
        salt = "smartvms_secure_salt_"
        return hashlib.sha256((salt + password).encode('utf-8')).hexdigest()

def verify_password(password, hashed_val):
    """Verify a password against its hash."""
    if HAS_BCRYPT:
        try:
            return bcrypt.checkpw(password.encode('utf-8'), hashed_val.encode('utf-8'))
        except Exception:
            # If bcrypt format fails (e.g. hash was generated by SHA-256 fallback), try fallback
            pass
    
    salt = "smartvms_secure_salt_"
    fallback_hash = hashlib.sha256((salt + password).encode('utf-8')).hexdigest()
    return fallback_hash == hashed_val

def get_db_connection():
    """Create and return a database connection with foreign key support."""
    os.makedirs(DB_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn

def initialize_database():
    """Create all tables and seed default data if database is empty."""
    os.makedirs(DB_DIR, exist_ok=True)
    conn = get_db_connection()
    cursor = conn.cursor()

    # 1. Users Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        full_name TEXT NOT NULL,
        role TEXT CHECK(role IN ('Admin', 'Security', 'Receptionist')) NOT NULL,
        email TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    """)

    # 2. Departments Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS departments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE NOT NULL
    );
    """)

    # 3. Employees Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS employees (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        department_id INTEGER,
        email TEXT UNIQUE NOT NULL,
        mobile TEXT NOT NULL,
        FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
    );
    """)

    # 4. Visitors Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS visitors (
        id TEXT PRIMARY KEY,
        full_name TEXT NOT NULL,
        gender TEXT NOT NULL,
        mobile TEXT NOT NULL,
        email TEXT,
        address TEXT,
        company_name TEXT,
        purpose TEXT NOT NULL,
        employee_id INTEGER,
        department_id INTEGER,
        id_proof_type TEXT,
        status TEXT CHECK(status IN ('Registered', 'CheckedIn', 'CheckedOut')) DEFAULT 'Registered',
        photo_path TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
        FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
    );
    """)

    # 5. Check-In/Out Records Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS check_records (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        visitor_id TEXT NOT NULL,
        check_in_time TIMESTAMP,
        check_out_time TIMESTAMP,
        duration_minutes INTEGER,
        checked_in_by INTEGER,
        checked_out_by INTEGER,
        FOREIGN KEY (visitor_id) REFERENCES visitors(id) ON DELETE CASCADE,
        FOREIGN KEY (checked_in_by) REFERENCES users(id) ON DELETE SET NULL,
        FOREIGN KEY (checked_out_by) REFERENCES users(id) ON DELETE SET NULL
    );
    """)

    # 6. System Audit Logs Table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS audit_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER,
        action TEXT NOT NULL,
        details TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );
    """)

    # Check if we need to seed data
    cursor.execute("SELECT COUNT(*) FROM users;")
    if cursor.fetchone()[0] == 0:
        print("Seeding database with default settings...")
        
        # Seed Users
        admin_hash = hash_password("admin123")
        reception_hash = hash_password("reception123")
        security_hash = hash_password("security123")
        
        cursor.execute("INSERT INTO users (username, password_hash, full_name, role, email) VALUES (?, ?, ?, ?, ?);",
                       ("admin", admin_hash, "System Administrator", "Admin", "admin@smartvms.com"))
        cursor.execute("INSERT INTO users (username, password_hash, full_name, role, email) VALUES (?, ?, ?, ?, ?);",
                       ("reception", reception_hash, "Reception Desk Agent", "Receptionist", "receptionist@smartvms.com"))
        cursor.execute("INSERT INTO users (username, password_hash, full_name, role, email) VALUES (?, ?, ?, ?, ?);",
                       ("security", security_hash, "Security Officer", "Security", "security@smartvms.com"))

        # Seed Departments
        departments = ["Executive Office", "Human Resources", "Information Technology", "Finance", "Operations", "Research & Development"]
        for dept in departments:
            cursor.execute("INSERT INTO departments (name) VALUES (?);", (dept,))

        # Seed Employees
        employees = [
            ("John Doe", 1, "john.doe@company.com", "+1-555-0101"),
            ("Alice Smith", 2, "alice.smith@company.com", "+1-555-0102"),
            ("Bob Johnson", 3, "bob.johnson@company.com", "+1-555-0103"),
            ("Charlie Brown", 3, "charlie.brown@company.com", "+1-555-0104"),
            ("Diana Prince", 4, "diana.prince@company.com", "+1-555-0105"),
            ("Edward Elric", 5, "edward.elric@company.com", "+1-555-0106"),
            ("Fiona Gallagher", 6, "fiona.gallagher@company.com", "+1-555-0107")
        ]
        for emp in employees:
            cursor.execute("INSERT INTO employees (name, department_id, email, mobile) VALUES (?, ?, ?, ?);", emp)
            
        conn.commit()
        print("Database initialized and seeded successfully.")
    
    conn.close()

if __name__ == "__main__":
    initialize_database()
